export const data = [{"Category": "Home","Task Name":"NoSQL","Priority":1,"Deadline":"07/19/2021","Details":"natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue"},
{"Category": "Home","Task Name":"Economic Modeling","Priority":1,"Deadline":"05/06/2021","Details":"bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue"},
{"Category": "Other","Task Name":"LTD","Priority":5,"Deadline":"01/12/2021","Details":"amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo"},
{"Category": "Misc","Task Name":"Software Design","Priority":3,"Deadline":"01/03/2021","Details":"ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit"},
{"Category": "Home","Task Name":"NCBI","Priority":1,"Deadline":"12/18/2020","Details":"velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum"},
{"Category": "Work","Task Name":"Compliance Oversight","Priority":1,"Deadline":"12/15/2020","Details":"sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris"},
{"Category": "Work","Task Name":"PDP","Priority":5,"Deadline":"11/30/2020","Details":"in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus"},
{"Category": "Other","Task Name":"Evangelism","Priority":4,"Deadline":"04/06/2021","Details":"ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec"},
{"Category": "Misc","Task Name":"Financial Mgmt","Priority":5,"Deadline":"04/01/2021","Details":"erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus"},
{"Category": "Home","Task Name":"CTMS","Priority":1,"Deadline":"10/31/2020","Details":"primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est"}
]
